### ISSUE TITLE
It would be great if this initialised the GIT Repo for me

### ISSUE THREAD

**Issue by aclifford85** [Branchout/branchout#1]
The tool works well but I find the need to clone the repo first is something that could have been handled by the initialisation. If you're interacting with GIT through the local context (i.e. whatever git repo is currently in the scope) why not also provide the means to initialise that context. So;
git clone git@git.somerepo
branchout init 

would be 
branchout init git@git.somerep:org/reponame

If it doesn't exist - just create one (git init with the name being extracted from the argument).

**Comment by stickycode** [comment]
So the first step is complete ```init url``` it requires that the remote projects exists but does not require is its configured for Branchout, that will happen automatically

git init git@git.somerep:org/reponame
git init https://github.com/owner/reponame
git init git@git.somerep:org/reponame local_projects_name

The second requires GitHub or BitBucket or xxx integration which is out of scope at the moment.
