### ISSUE TITLE
branchout clone results in phantom `unknown revision or path not in the working tree `error`

### ISSUE THREAD

**Issue by jonathanptew** [Branchout/branchout#30]
 ~/projects/org   master  branchout clone group-itemname-subname
Cloning group-itemname-subname
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
 ~/projects/org   master  ls -l
total 16
-rw-r--r--  1 blahblah  staff   66 22 May 12:46 Branchoutfile
-rw-r--r--  1 blahblah  staff  110 22 May 13:07 Branchoutprojects
drwxr-xr-x  3 blahblah  staff   96 22 May 13:07 group-itemname-subname

**Comment by stickycode** [comment]
@jonathanptew in this case the repository is bare, the error could be better I guess, make say that the repository is bare
