### ISSUE TITLE
On windows, use ~/ style path to localRepository, not absolute /c/* style

### ISSUE THREAD

**Issue by fredcooke** [Branchout/branchout#48]

**Comment by fredcooke** [comment]
That was wrong, `~/` is no good either, needs to be `${user.home}/`

**Comment by stickycode** [comment]
@fredcooke in maven settings?

**Comment by stickycode** [comment]
already fixed

**Comment by fredcooke** [comment]
Do you have a fixed in commit hash for us? :-D thanks, good work.

**Comment by stickycode** [comment]
Not sure it's been a while didn't look back in history

**Comment by fredcooke** [comment]
False, not fixed, now fixed, see PR #67

**Comment by fredcooke** [comment]
That ought to do it. Other one had a mistake, lax code review, and premature merge while I was still manually testing on windows :-D
