### ISSUE TITLE
Error: Empty installation during install process

### ISSUE THREAD

**Issue by blair-willems** [Branchout/branchout#74]
Received the following error message during installation with brew. This halts execution of any additional packages being installed in the command.

<img width="695" alt="Screen Shot 2021-05-28 at 10 17 10 AM" src="https://user-images.githubusercontent.com/84689574/119906844-22d6a980-bfa3-11eb-8672-5dd808388861.png">

**Comment by fredcooke** [comment]
Yes, best to install other things separately for now. The package really is empty and Mike needs to add something into it, even if artificially, to quash that.

**Comment by practiv-vigneshsivapragasam** [comment]
Work around to install other packages minus branchout by doing the following to bypass the branchout installation
`brew pin branchout`

**Comment by vigneshsivapragasam** [comment]
Work around to install other packages minus branchout by doing the following to bypass the branchout installation
`brew pin branchout`

**Comment by stickycode** [comment]
see https://github.com/Branchout/homebrew-branchout/pull/2

**Comment by stickycode** [comment]
Seems like it works for install but not upgrade

**Comment by fredcooke** [comment]
Doh! That sucks.
